from scipy import *
from scipy.linalg import *

def solution():
    m1 = array( [ [ 1/2, 1/3 ], [ -2/7, 2/ 8 ]] )
    m2 = array( [ [ -1/3, 2/7 ], [ 2/5, -1/7 ]] )
    m3 = array( [ [ -1/5,2/3], [1/8, 3/11] ] )
    p = array( [ [ -1/30, 2/21 ], [ 41/210, -23/196 ] ] )
    I = array( [ [ 42, -56 ], [ 48, 84 ]] ) / 37
    print("This is part 1\n")
    print('The product of m1 and m2 is')
    print(dot(m1, m2))
    print("\n")
    print('The difference between m1*m2 and p is')
    print(dot(m1, m2) - p)
    print("\n")
    print("\n")
    print("This is part 2\n")
    print('The inverse of m1 is')
    print(inv(m1))
    print("\n")
    print('The difference between inverse of m1 and I is')
    print(inv(m1)-I)
    print("\n")
    print("\n")
    print("This is part 3\n")
    print("The product (m1*m2)*m3 is:")
    print(dot(dot(m1,m2), m3))
    print("\n")
    print("The product m1*(m2*m3) is:")
    print(dot(m1, dot(m2, m3)))
    print("\n")
    print("\n")

    print("This is part 4\n")
    print('The difference between m1*(m2+m3) and m1*m2+m1*m3 is')
    print(dot(m1, m2+m3)-(dot(m1, m2) + dot(m1, m3)))
    print('\n')
    print('the difference between (m1+m2)*m3 and (m1*m3+m2*m3) is')
    print(dot(m1 + m2, m3) - (dot(m1, m3) + dot(m2, m3)))
    print('\n')
    print("\n")

    print("This is part 5\n")
    v = array( [ 3.0, -1])
    print("the difference between m1(m2(v)) and (m1*m2)(v) is ")
    print(dot(m1, dot(m2, v)) - dot(dot(m1,m2), v))
    print('\n')
    print("\n")

    print("This is part 6\n")
    print('The difference between det(m1)*det(m2) and det(m1*m2) is ')
    print(det(m1)*det(m2) - det(dot(m1,m2)))
    print('\n')
    print("\n")

    print("This is part 7\n")
    print("The product of m1 and inv(m1) is ")
    print(dot(m1, inv(m1)))
    print('\n')
    print("The product of inv(m1) and m1 is ")
    print(dot(inv(m1), m1))
    print('\n')
